#! /bin/sh

#----------------------------------------------------
# 			BSPWM autostart
#----------------------------------------------------
killall polybar &
pgrep -x sxhkd > /dev/null || sxhkd & $HOME/.config/bspwm/scripts/screen_layout.sh &
$HOME/.config/bspwm/scripts/lefthand.sh &
$HOME/.config/bspwm/scripts/polybar_start.sh &
flameshot &
picom -CGb &
nm-applet &
wmname compiz & 
xsetroot -cursor_name left_ptr &
feh $HOME/.config/bspwm/wallpaper/bear.jpg --bg-center &
inkscape-figures watch &
dunst &

xmodmap -e "add mod4 = ISO_Left_Tab" &
xmodmap -e "add mod4 = backslash" &

#----------------------------------------------------
# 			BSPWM monitor setup
#----------------------------------------------------
tags=(1 2 3 4 5 6 7 8 9)

index=0
monitors=$(xrandr | grep " connected " | awk '{ print$1 }')
monitor_count=$(xrandr | grep " connected " | awk '{ print$1 }' | wc -l)
for monitor in $monitors
do
	if [ $((monitor_count-1)) -eq $index ]
	then
		bspc monitor $monitor -d ${tags[@]:$index}
	else
		bspc monitor $monitor -d $((index+1))
	fi

	index=$((index+1))
done

#----------------------------------------------------
# 			BSPWM config settings
#----------------------------------------------------
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config normal_border_color '#545454'
bspc config focused_border_color '#ff7b00'
bspc config border_width 1


#----------------------------------------------------
# 			BSPWM rule settings
#----------------------------------------------------
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

