#! /bin/sh

~/myscripts/.lefthandmouse
~/.config/polybar/launch.sh

sxhkd &

bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor DP-3 -d 1 2 3 4 5

#BSPWM configuration
bspc config border_radius       0
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          5
bspc config bottom_padding       5
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_diRstance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

