#! /bin/bash
#
# Example panel for lemonbar

# Souce the panel colors script
. $HOME/.config/bspwm/scripts/panel_colors

# Receives the name of the monitor that the bar is being places on
MONITOR_NAME_BAR=$1

# Variables used
monitor=
focused_monitor=
workspaceNumber=
tag=
desktops=()


while read -r line ; do

	case $line in
		clock*)
			# clock output

			clock="%{F#ffbe57}%{B$COLOR_DEFAULT_BG} ${line:5} %{B-}%{F-}"
			;;
		disk*)
			disk="%{F#6bbf9f}%{B$COLOR_DEFAULT_BG}  ${line:4} %{B-}%{F-}"
			;;
		memory*)
			memory="%{A:alacritty -e htop:}%{F#ff8c8c}%{B$COLOR_DEFAULT_BG}  ${line:6} %{B-}%{F-}%{A}"
			;;
		cpu*)
			cpu="%{F#88c8f2}%{B$COLOR_DEFAULT_BG}  ${line:3} %{B-}%{F-}"
			;;
		vol*)
			if [ ${line:3} -lt 1 ]
			then
				vol="%{F#ffc478}%{B$COLOR_DEFAULT_BG}  ${line:3}% %{B-}%{F-}"
			elif [ ${line:3} -gt 1 ] && [ ${line:3} -lt 40 ]
			then
				vol="%{F#ffc478}%{B$COLOR_DEFAULT_BG}  ${line:3}% %{B-}%{F-}"
			elif [ ${line:3} -gt 40 ] && [ ${line:3} -lt 70 ] 
			then
				vol="%{F#ffc478}%{B$COLOR_DEFAULT_BG}  ${line:3}% %{B-}%{F-}"
			elif [ ${line:3} -gt 70 ]
			then
				vol="%{F#ffc478}%{B$COLOR_DEFAULT_BG}  ${line:3}% %{B-}%{F-}"
			fi

			;;
		title*)
			# Check if the there is a node on the window
		#	title_name=
			if [ -z ${line:5} ]
			then
				title_name="empty"
			else
				title_name=${line:5}
			fi

			# xtitle output
			if [ $focused_monitor = $MONITOR_NAME_BAR ]
			then
				title="%{F$COLOR_TITLE_FG_FOCUSED}%{B$COLOR_TITLE_BG_FOCUSED} $title_name %{B-}%{F-}"
			else
				title="%{F$COLOR_TITLE_FG_UNFOCUSED}%{B$COLOR_TITLE_BG_UNFOCUSED} $title_name %{B-}%{F-}"

			fi

			;;
		W*)
			# bspwm workspaces

			IFS=':' read -ra splitArray <<< "${line:1}"
			
			for item in "${splitArray[@]}"
			do
				case $item in
					[M]* )
						monitor="${item:1}"
						focused_monitor=$monitor

						;;		
					[m]* )
						monitor="${item:1}"

						;;
					[FO]* )
						if [ $monitor = $MONITOR_NAME_BAR ]
						then
							workspaceNumber=${item:1}
							tag="%{F#66f5fa}[%{F-}%{F$COLOR_OCCUPIED_FG}${item:1}%{F-}%{F#66f5fa}]%{F-}"
							desktops[$workspaceNumber]=$tag
						else
							workspaceNumber=${item:1}
							tag="%{F#66f5fa}'%{F-}%{F$COLOR_OCCUPIED_FG}${item:1}%{F-}%{F#66f5fa}'%{F-}"
							desktops[$workspaceNumber]=$tag
						fi

						;;
					[f]* )
							workspaceNumber=${item:1}
							tag="%{F$COLOR_UNOCCUPIED_FG} ${item:1} %{F-}"
							desktops[$workspaceNumber]=$tag

						;;
					[o]* )
							workspaceNumber=${item:1}
							tag="%{F$COLOR_OCCUPIED_FG} ${item:1} %{F-}"
							desktops[$workspaceNumber]=$tag
						;;

					* )
						continue
				esac
			done

			# Set the wm variable as the output of the array
			wm=" ${desktops[@]}"
			;;
	esac
	echo -e "%{l}${wm} ${title}%{r}${vol}${cpu}${memory}${disk}${clock}%{O5}%{O-}"
done
