#!/bin/bash

. $HOME/.config/bspwm/scripts/panel_colors

MONITOR_NAME_BAR=$1

while read -r line ; do

	case $line in
		title*)
			# Check if the there is a node on the window
		#	title_name=
			if [ -z "${line:5}" ]
			then
				title_name="empty"
			else
				title_name=${line:5}
			fi

			# xtitle output
			if [ $focused_monitor = $MONITOR_NAME_BAR ]
			then
				title="%{F$COLOR_TITLE_FG_FOCUSED}%{B$COLOR_TITLE_BG_FOCUSED} $title_name %{B-}%{F-}"
			else
				title="%{F$COLOR_TITLE_FG_UNFOCUSED}%{B$COLOR_TITLE_BG_UNFOCUSED} $title_name %{B-}%{F-}"

			fi

			;;
		W*)
			# bspwm workspaces

			IFS=':' read -ra splitArray <<< "${line:1}"
			
			for item in "${splitArray[@]}"
			do
				case $item in
					[M]* )
						monitor="${item:1}"
						focused_monitor=$monitor

						;;		
					[m]* )
						monitor="${item:1}"

						;;
					[FO]* )
						if [ $monitor = $MONITOR_NAME_BAR ]
						then
							workspaceNumber=${item:1}
							tag="%{F#66f5fa}[%{F-}%{F$COLOR_OCCUPIED_FG}${item:1}%{F-}%{F#66f5fa}]%{F-}"
							desktops[$workspaceNumber]=$tag
						else
							workspaceNumber=${item:1}
							tag="%{F#66f5fa}'%{F-}%{F$COLOR_OCCUPIED_FG}${item:1}%{F-}%{F#66f5fa}'%{F-}"
							desktops[$workspaceNumber]=$tag
						fi

						;;
					[f]* )
							workspaceNumber=${item:1}
							tag="%{F$COLOR_UNOCCUPIED_FG} ${item:1} %{F-}"
							desktops[$workspaceNumber]=$tag

						;;
					[o]* )
							workspaceNumber=${item:1}
							tag="%{F$COLOR_OCCUPIED_FG} ${item:1} %{F-}"
							desktops[$workspaceNumber]=$tag
						;;

					* )
						continue
				esac
			done

			# Set the wm variable as the output of the array
			wm=" ${desktops[@]}"
			;;
		*)
			;;
	esac
	printf "%s\n" "${wm} ${title}"
done
